# Generated by Django 5.1.7 on 2025-03-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_rename_specialty_doctor_specialtiy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialtiy',
            new_name='speciality',
        ),
    ]
