# Generated by Django 5.1.7 on 2025-03-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_rename_specialtiy_doctor_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
